# ==========================================
# 用户端 Cloud Run 服务配置
# ==========================================
# 使用方法：
# gcloud run services replace cloudrun-user.yaml --region=asia-east1
# ==========================================

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ppanel-user-web
  labels:
    app: ppanel
    component: user-web
spec:
  template:
    metadata:
      annotations:
        # 自动扩缩容配置
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        # CPU 节流
        run.googleapis.com/cpu-throttling: 'true'
        # 启动 CPU 加速
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      # 容器并发请求数
      containerConcurrency: 80
      # 请求超时（秒）
      timeoutSeconds: 300
      # 服务账号（如需要可配置）
      # serviceAccountName: your-service-account@your-project.iam.gserviceaccount.com
      
      containers:
      - name: user-web
        # 镜像将由构建流程自动设置
        image: gcr.io/PROJECT_ID/ppanel-user-web:latest
        
        ports:
        - name: http1
          containerPort: 3000
        
        # 环境变量
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.yourdomain.com"
        - name: NEXT_PUBLIC_SITE_URL
          value: "https://user.yourdomain.com"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: NODE_ENV
          value: "production"
        # 可选：从 Secret Manager 读取
        # - name: API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: api-key
        #       key: latest
        
        # 资源限制
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
        
        # 健康检查
        startupProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 3
        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3

